server:
  port: ${SERVER_PORT:8081}

sparql:
  endpoint: ${SPARQL_ENDPOINT:http://localhost:8890/sparql}
  defaultGraphUri: ${DEFAULT_GRAPH:http://mu.semte.ch/graphs/privacy-centric-graph}
  appGraphUri: ${APP_GRAPH:http://mu.semte.ch/graphs/contacthub/141d9d6b-54af-4d17-b313-8d1c30bc3f5b/ChAdmin}
  sessionGraphUri: ${SESSION_GRAPH:http://mu.semte.ch/graphs/sessions}
  baseUrl: ${BASE_URL:https://data.lblod.info}
  queryStore:
    path: ${SPARQL_QUERY_STORE_PATH:classpath*:sparql}

spring:
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:512MB}
      max-file-size: ${MAX_FILE_SIZE:512MB}
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
