server:
  port: ${SERVER_PORT:8081}

sparql:
  endpoint: ${SPARQL_ENDPOINT:http://localhost:8890/sparql}
  defaultGraphUri: ${DEFAULT_GRAPH:http://mu.semte.ch/application}
  sessionGraphUri: ${SESSION_GRAPH:http://mu.semte.ch/graphs/sessions}
  baseUrl: ${BASE_URL:https://data.lblod.info}
  queryStore:
    path: ${SPARQL_QUERY_STORE_PATH:classpath*:sparql}

spring:
  servlet:
    multipart:
      max-request-size: ${MAX_REQUEST_SIZE:512MB}
      max-file-size: ${MAX_FILE_SIZE:512MB}
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
